spring:
  application:
    name: walmart-APIGateway
  cloud:
    gateway:
      routes:
        - id: JWTAuthService
          # uri: http://localhost:8084/
          uri: lb://WALMART-JWTAUTHSERVICE
          predicates:
            - Path=/jwt/**
        - id: OAuth2AuthService
          # uri: http://localhost:8085/
          uri: lb://WALMART-OAUTH2AUTHSERVICE
          predicates:
            - Path=/oauth2/**
server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#eureka:
#  instance:
#   hostname: localhost   

