spring:
  application:
    name: walmart-ExternalAPIService

server:
  port: 8087

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost